language: rust
cache:
  directories:
    - $HOME/.cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
branches:
  only:
    - master
    - auto
script:
  - cargo build -v --features strict
  - cargo test -v --features strict
  - cargo doc